//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookinglist
    {
        public int id { get; set; }
        public string eventname { get; set; }
        public string eventrate { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string contactnumber { get; set; }
        public string advanceamount { get; set; }
        public string paymentmode { get; set; }
        public string customerID { get; set; }
        public string bookingID { get; set; }
    }
}
