//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventlist
    {
        public int id { get; set; }
        public string eventname { get; set; }
        public string eventdescription { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public string image4 { get; set; }
        public string image5 { get; set; }
        public string image6 { get; set; }
        public string eventfeature { get; set; }
        public string eventrate { get; set; }
        public string advancerate { get; set; }
        public string Contactperson { get; set; }
        public string Contactnumber { get; set; }
    }
}
